title: "Example Website"
description: "Welcome to my website and blog."
author: "Bob the Builder"

url: "https://tamkeen-cloud-engineering.github.io/"
baseurl: "/example-personal-website"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
